-- DB2 for z/OS migration for the EMPRESA record shared by the API and CICS.
-- Apply once under the LIFECORE schema before deploying either writer.
CREATE TABLE LIFECORE.EMPRESA (
    CD_EMPRESA              INTEGER NOT NULL
                            GENERATED ALWAYS AS IDENTITY
                            (START WITH 1 INCREMENT BY 1),
    NR_CODIGO               CHAR(6) NOT NULL,
    NM_RAZAO_SOCIAL         VARCHAR(80) NOT NULL,
    NM_NOME_REDUZIDO        VARCHAR(30),
    CD_CNPJ                 CHAR(14) NOT NULL,
    TP_EMPRESA              CHAR(2) NOT NULL,
    NR_SUSEP                CHAR(10),
    VL_CAPITAL_VINCULADO    DECIMAL(15,2),
    VL_CAPITAL_SUBSCRITO    DECIMAL(15,2),
    VL_ACEITE_COBRANCA      DECIMAL(10,2),
    CD_STATUS               CHAR(2) NOT NULL DEFAULT 'AT',
    DT_INCLUSAO             CHAR(8) NOT NULL,
    ID_USUARIO_INCL         CHAR(8) NOT NULL,
    TS_INCLUSAO             TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    TS_ALTERACAO            TIMESTAMP,
    CONSTRAINT PK_EMPRESA PRIMARY KEY (CD_EMPRESA),
    CONSTRAINT UK_EMPRESA_CNPJ UNIQUE (CD_CNPJ),
    CONSTRAINT UK_EMPRESA_COD UNIQUE (NR_CODIGO),
    CONSTRAINT CK_EMPRESA_TP CHECK (TP_EMPRESA IN ('SE','ES','CO','CN','RE')),
    CONSTRAINT CK_EMPRESA_ST CHECK (CD_STATUS IN ('AT','IN'))
);
