-- Staging persistente de segurados antes da configuração da apólice.
-- As colunas de salário, cargo e capital da origem não são armazenadas.
CREATE TABLE LIFECORE.IMPORTACAO_INICIAL (
    ID_IMPORTACAO       CHAR(36) NOT NULL,
    CD_STATUS           CHAR(2) NOT NULL DEFAULT 'RV',
    QT_REGISTROS        INTEGER NOT NULL,
    ID_USUARIO          CHAR(8) NOT NULL,
    TS_INCLUSAO         TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_IMPORTACAO_INICIAL PRIMARY KEY (ID_IMPORTACAO),
    CONSTRAINT CK_IMP_INICIAL_STATUS CHECK (CD_STATUS IN ('RV','LI','CA'))
);

CREATE TABLE LIFECORE.IMPORTACAO_INICIAL_ITEM (
    ID_IMPORTACAO       CHAR(36) NOT NULL,
    NR_LINHA            INTEGER NOT NULL,
    CD_SUBESTIPULANTE   VARCHAR(60) NOT NULL,
    CD_MODULO           VARCHAR(60) NOT NULL,
    NM_SEGURADO         VARCHAR(120) NOT NULL,
    CD_CPF              VARCHAR(20) NOT NULL,
    DT_NASCIMENTO       CHAR(8),
    DT_ADMISSAO         CHAR(8),
    DS_ERROS            VARCHAR(1000),
    CD_STATUS           CHAR(2) NOT NULL DEFAULT 'RV',
    CONSTRAINT PK_IMP_INICIAL_ITEM
        PRIMARY KEY (ID_IMPORTACAO, NR_LINHA),
    CONSTRAINT FK_IMP_INICIAL_ITEM
        FOREIGN KEY (ID_IMPORTACAO)
        REFERENCES LIFECORE.IMPORTACAO_INICIAL (ID_IMPORTACAO),
    CONSTRAINT CK_IMP_INICIAL_ITEM_STATUS CHECK (CD_STATUS IN ('RV','ER','LI'))
);

CREATE INDEX LIFECORE.IX_IMP_INICIAL_CPF
    ON LIFECORE.IMPORTACAO_INICIAL_ITEM (CD_CPF);
